apiVersion: apps/v1
kind: Deployment
metadata:
  name: curing-server
  labels:
    app: curing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curing-server
  template:
    metadata:
      labels:
        app: curing-server
    spec:
      containers:
      - name: server
        image: quay.io/benarmosec/curing:1.0-server
        ports:
        - containerPort: 8888
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: curing-server-service
  labels:
    app: curing-server
spec:
  type: ClusterIP
  ports:
  - port: 8888
    targetPort: 8888
    protocol: TCP
    name: http
  selector:
    app: curing-server
